
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: db/development_earthquake
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: db/test_earthquake
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: db/production_earthquake
  pool: 5
  timeout: 5000
